---
- name: install pnpm needs
  apt:
    pkg:
      - "ca-certificates"
      - "gnupg"
      - "curl"
  become: true
- name: Check if node key exists
  stat:
    path: /usr/share/keyrings/nodesource.gpg
  register: stat_result_nodesource
- name: ensure node gpg key is in place
  shell: |
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /usr/share/keyrings/nodesource.gpg
    echo "deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_22.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
  become: true
  when: not stat_result_nodesource.stat.exists
- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest
  become: true
- name: install nodejs
  apt:
    pkg:
      - "nodejs"
      - "build-essential"
  become: true
- name: Check if pnpm exists
  stat:
    path: /home/TimberBuddy/.local/share/pnpm/pnpm
  register: stat_result_pnpm
- name: ensure pnpm is installed
  shell: |
    curl -fsSL https://get.pnpm.io/install.sh | sh -
  ignore_errors: true
  when: not stat_result_pnpm.stat.exists
- name: Check if timberbuddy git repo exists
  stat:
    path: /home/TimberBuddy/timberbuddy/.git
  register: stat_result_tb_git
- name: set upstream and fetch
  shell: |
    git remote set-url origin https://jesssullivan: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@github.com/jesssullivan/timberbuddy
    git fetch
    git switch remote-dev
    git pull
  args:
    chdir: /home/TimberBuddy/timberbuddy/
  when: stat_result_tb_git.stat.exists
- name: clone timberbuddy repo
  shell: |
    gh repo clone Jesssullivan/timberbuddy
  when: not stat_result_tb_git.stat.exists
- name: ensure node depends are installed
  command: /home/TimberBuddy/.local/share/pnpm/pnpm install
  args:
    chdir: /home/TimberBuddy/timberbuddy/
- name: build timberbuddy
  command: /home/TimberBuddy/.local/share/pnpm/pnpm run build
  args:
    chdir: /home/TimberBuddy/timberbuddy/
- name: Ensure Timber Buddy control interface service is in place
  template:
    src: TimberBuddyInterfaceService.service.j2
    dest: /etc/systemd/system/TimberBuddyInterfaceService.service
    mode: 0644
  become: yes
- name: Ensure Timber Buddy Interface Service is fully stopped
  systemd:
    name: TimberBuddyInterfaceService
    state: stopped
  become: yes
- name: Ensure Timber Buddy Interface Service is running
  systemd:
    name: TimberBuddyInterfaceService
    state: started
  become: yes