---
- name: check i2c status
  command: raspi-config nonint get_i2c
  register: i2c_state
  become: true
- name: enable linger
  command:  loginctl enable-linger
  become: true
- name: enable i2c
  shell: |
    raspi-config nonint do_i2c 0
  become: true
  when: i2c_state != 0
- name: ensure wlan power and splashboot is off
  blockinfile:
    dest: /boot/firmware/config.txt
    block: |
      dtoverlay=vc4-kms-v3d
      dtoverlay=vc4-kms-dsi-7inch
  become: true
- name: insert empty line before the marker
  lineinfile:
    dest: /boot/firmware/config.txt
    insertbefore: '^# TIMBERBUDDY ANSIBLE MANAGED BLOCK$'
    line: ''
  become: true
- name: install pre depends
  apt:
    pkg:
      - "lsb-release"
      - "curl"
  become: true
- name: Ensure network persistence
  template:
    src: network_up.sh.j2
    dest: "~/network_up.sh"
    mode: "+x"
  become: true
- name: Run network persistence every 5 minutes
  become: yes
  cron:
    name: "net_persist"
    user: "root"
    weekday: "*"
    minute: "5"
    hour: "*"
    job: "./network_up.sh > /log/network.log"
    state: present
#- name: sync boot cmdline script
#  template:
#    src: cmdline.txt
#    dest: "/boot/firmware/cmdline.txt"
#  become: yes
#- name: ensure pix script is updated
#  template:
#    src: pix.script
#    dest: "/usr/share/plymouth/themes/pix/pix.script"
#  become: yes
#- name: Place neko girl for startup
#  synchronize:
#    src: pix.png
#    dest: "/usr/share/plymouth/themes/pix/splash.png"
#  become: yes
#- name: rebuild boot theme
#  shell: |
#    plymouth-set-default-theme --rebuild-initrd pix
#  become: true
- name: reboot the machine
  reboot:
    reboot_timeout: 300
  become: true