---
- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest
  become: true
- name: Check Brightness.zip exists
  stat:
    path: Brightness.zip
  register: stat_result_brightness
- name: install backlight util in default location
  shell: |
    wget https://files.waveshare.com/upload/f/f4/Brightness.zip
    unzip Brightness.zip
    cd Brightness
    sudo chmod +x install.sh
    ./install.sh
  when: not stat_result_brightness.stat.exists
  become: true
- name: preform pulse brightness sanity check
  shell: |
    echo 100 | sudo tee /sys/class/backlight/*/brightness && sleep 1
    echo 0 | sudo tee /sys/class/backlight/*/brightness && sleep 1
    echo 100 | sudo tee /sys/class/backlight/*/brightness && sleep 1
    echo 255 | sudo tee /sys/class/backlight/*/brightness && sleep 1
    echo 100 | sudo tee /sys/class/backlight/*/brightness && sleep 1
    echo 0 | sudo tee /sys/class/backlight/*/brightness && sleep 1
    echo 100 | sudo tee /sys/class/backlight/*/brightness && sleep 1
    echo 200 | sudo tee /sys/class/backlight/*/brightness
- name: reboot the machine
  reboot:
    reboot_timeout: 300
  become: true